version: "3.8"

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  mariadb:
    image: yobasystems/alpine-mariadb:armhf
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - internal_net

  backend:
    platform: linux/arm/v7
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules   # évite les conflits node_modules entre local et conteneur
    environment:
      SECRETKEY: ${SECRETKEY}
      PORT: ${PORT}
      HOST: ${HOST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      CLIENT_URL: ${CLIENT_URL}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mariadb
    networks:
      - internal_net

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    networks:
      - internal_net

volumes:
  mariadb_data:
  caddy_data:
  caddy_config:

    